[package]
name = "bitio-rs"
version = "0.1.2"
edition = "2024"
description = "ğŸš€A lightweight Rust library for bit-level I/O: read, peek, write, with both big-endian and little-endian support."
authors = ["ubizhang@hotmail.com"]
license = "GPL-3.0-or-later"
repository = "https://github.com/F2077/bitio-rs"
#documentation = "https://github.com/F2077/bitio"

[dev-dependencies]
criterion = "0.4"
itertools = "0.10.5"

[features]
default = []
bench = []  # æ˜¾å¼å£°æ˜ bench ç‰¹æ€§

[[bench]]
name = "read"
harness = false

[dependencies]
